services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount database directory for persistence
      - ./data:/app/data
      # Mount main.py for development (optional - remove for production)
      - ./main.py:/app/main.py
    environment:
      - DATABASE_FILE=/app/data/database.db
    restart: unless-stopped
    
  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  #   restart: unless-stopped
